project:
    project_name: mock_project
    description: mock_description
    version: mock_version

input_data:
    data_location: mock
    local_directory: mockdata/mockdata
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: 'https://github.com/RADAR-base-Analytics/mockfeatures'
      feature_groups:
          - MockFeatureGroup

output_data:
    output_location: local
    local_directory: output/mockdata
    data_format: csv
